//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gostar.Setting.DA.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Branch()
        {
            this.BranchRegionWork = new HashSet<BranchRegionWork>();
        }
    
        public long ID { get; set; }
        public Nullable<long> ParentID { get; set; }
        public long BranchAddressID { get; set; }
        public string Title { get; set; }
        public string Code { get; set; }
        public Nullable<long> HeadPersonID { get; set; }
        public string BranchPhoneNo { get; set; }
        public string BranchEmail { get; set; }
        public bool IsCentral { get; set; }
        public string Comment { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<long> LeftIndex { get; set; }
        public Nullable<long> RightIndex { get; set; }
        public Nullable<long> Depth { get; set; }
        public string OldCode { get; set; }
    
        public virtual Branch Branch1 { get; set; }
        public virtual Branch Branch2 { get; set; }
        public virtual BranchAddress BranchAddress { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BranchRegionWork> BranchRegionWork { get; set; }
    }
}
