//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gostar.Setting.DA.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public long ID { get; set; }
        public long UserID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int EntityID { get; set; }
        public int ActionTypeID { get; set; }
        public Nullable<long> RecordID { get; set; }
        public string Message { get; set; }
        public Nullable<long> GroupID { get; set; }
        public Nullable<long> RegistrantPersonID { get; set; }
        public string RegistrantPersonFullName { get; set; }
        public string GroupName { get; set; }
    }
}
