//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gostar.Setting.DA.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegionAgent
    {
        public long ID { get; set; }
        public System.DateTime StartDate { get; set; }
        public long PersonID { get; set; }
        public long RegionID { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual Region Region { get; set; }
    }
}
