//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gostar.Setting.DA.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RuleTag
    {
        public long ID { get; set; }
        public long RuleID { get; set; }
        public long FormTypeID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual FormType FormType { get; set; }
        public virtual Rule Rule { get; set; }
    }
}
