//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gostar.Setting.DA.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SettingEntities : DbContext
    {
        public SettingEntities()
            : base("name=SettingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Area> Area { get; set; }
        public virtual DbSet<Branch> Branch { get; set; }
        public virtual DbSet<BranchAddress> BranchAddress { get; set; }
        public virtual DbSet<BranchRegionWork> BranchRegionWork { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<Currency> Currency { get; set; }
        public virtual DbSet<ExchangeRate> ExchangeRate { get; set; }
        public virtual DbSet<FormType> FormType { get; set; }
        public virtual DbSet<GeneratedForm> GeneratedForm { get; set; }
        public virtual DbSet<Log> Log { get; set; }
        public virtual DbSet<OrganizationalChart> OrganizationalChart { get; set; }
        public virtual DbSet<Prefix> Prefix { get; set; }
        public virtual DbSet<Region> Region { get; set; }
        public virtual DbSet<RegionAgent> RegionAgent { get; set; }
        public virtual DbSet<Rule> Rule { get; set; }
        public virtual DbSet<RuleTag> RuleTag { get; set; }
        public virtual DbSet<Sector> Sector { get; set; }
        public virtual DbSet<Statement> Statement { get; set; }
        public virtual DbSet<StatementSubsystem> StatementSubsystem { get; set; }
        public virtual DbSet<Subpart> Subpart { get; set; }
        public virtual DbSet<Subsystem> Subsystem { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Typeoforganization> Typeoforganization { get; set; }
        public virtual DbSet<Zone> Zone { get; set; }
    }
}
