//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gostar.Setting.DA.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatementSubsystem
    {
        public long ID { get; set; }
        public long StatementID { get; set; }
        public long SubsystemID { get; set; }
    
        public virtual Statement Statement { get; set; }
        public virtual Subsystem Subsystem { get; set; }
    }
}
