//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gostar.Setting.DA.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subsystem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Subsystem()
        {
            this.FormType = new HashSet<FormType>();
            this.StatementSubsystem = new HashSet<StatementSubsystem>();
            this.Subpart = new HashSet<Subpart>();
        }
    
        public long ID { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsSystem { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> RunOrder { get; set; }
        public bool IsPart { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormType> FormType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StatementSubsystem> StatementSubsystem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subpart> Subpart { get; set; }
    }
}
